### PR TITLE
Fix build for android targets

### LINKED ISSUE #349: Fails to compile on android.
Relevant code:

https://github.com/pop-os/cosmic-text/blob/166b59f560c551dab391a864f7c1f503c1e18446/src/font/fallback/mod.rs#L12

Compiling cosmic-text v0.12.1 (https://github.com/pop-os/cosmic-text?rev=166b59f560c551dab391a864f7c1f503c1e18446#166b59f5)
error[E0432]: unresolved import `self::platform`
  --> C:\Users\coffee\.cargo\git\checkouts\cosmic-text-92dc585b4973ff15\166b59f\src\font\fallback\mod.rs:10:11
   |
10 | use self::platform::*;
   |           ^^^^^^^^ could not find `platform` in `self`

### PR DESCRIPTION
**Pull request by rparrett**
`cosmic-text` doesn't seem to be building for android.

Fixes #349 

```
error[E0432]: unresolved import `self::platform`
  --> /Users/me/src/cosmic-text/src/font/fallback/mod.rs:10:11
   |
10 | use self::platform::*;
   |           ^^^^^^^^ could not find `platform` in `self`
```

I found that reverting 829a59bd9567b1ce1dd38c2fd527cf9ff838625b seems to fix the issue. I tried to wrangle the `cfg` directives to make sure android gets `platform`. I'm not 100% confident this is the correct fix and I'm not really sure how to test with these other platforms. Please feel free to close for an alternative fix.

To reproduce, I am attempting to build Bevy for android following the [instructions](https://github.com/bevyengine/bevy/blob/main/examples/README.md#android) from the examples readme.

```
git clone https://github.com/rparrett/bevy --single-branch cosmic-13
cd cosmic-13/examples/mobile
rustup target add aarch64-linux-android
cargo install cargo-ndk
cargo ndk -t arm64-v8a -o android_example/app/src/main/jniLibs build
```

### CODE REVIEW

**Review by mnmaita — COMMENTED** [review]
Neat. This should fix https://github.com/pop-os/cosmic-text/issues/349 FWIW.

**Review by jackpot51 — APPROVED** [review]
